### PR TITLE
[WIP] add gitignore and license files

### PR DESCRIPTION
**Pull request by githubstudent**
:warning: This is a work in progress, do not merge yet :warning: 
## Todo
- [x] Gitignore
- [ ] LICENSE

### CODE REVIEW

**Comment by githubstudent** [comment]
@brntbeer can you look at this? 

cc @orderedlist

**Comment by githubstudent** [comment]
also cc @githubteacher

**Comment by githubteacher** [comment]
Looks good so far, add the license and we're good

**Comment by orderedlist** [comment]
> add the license and we're good

:+1:

**Comment by githubstudent** [comment]
also cc #2 and #3

**Pull request merged**
